/*
 * File    : ExportToJSDlg.java
 * Created : 23-nov-2015 16:37
 * By      : fbusquets
 *
 * JClic - Authoring and playing system for educational activities
 *
 * Copyright (C) 2000 - 2005 Francesc Busquets & Departament
 * d'Educacio de la Generalitat de Catalunya
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details (see the LICENSE file).
 */
package edu.xtec.jclic.project;

import edu.xtec.util.Messages;
import edu.xtec.util.Options;
import edu.xtec.util.ResourceBridge;
import edu.xtec.util.StrUtils;
import java.awt.Component;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author Francesc Busquets (fbusquets@xtec.cat)
 * @version 23.11.15
 */
public class ExportToJSDlg extends javax.swing.JPanel {

  ResourceBridge rb;
  Options options;
  String outputFolder;
  boolean exportAll = true;
  boolean exportScorm = true;

  /**
   * Creates new form ExportToJSDlg
   */
  public ExportToJSDlg(ResourceBridge rb) {
    this.rb = rb;
    options = rb.getOptions();
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    exportLb = new javax.swing.JLabel();
    outputFolderLb = new javax.swing.JLabel();
    outputFolderText = new javax.swing.JTextField();
    outputFolderBtn = new javax.swing.JButton();
    javax.swing.JLabel spacer2 = new javax.swing.JLabel();
    allPrjChk = new javax.swing.JCheckBox();
    exportScormChk = new javax.swing.JCheckBox();

    setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
    setLayout(new java.awt.GridBagLayout());

    exportLb.setText(options.getMsg("export_project_desc"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    add(exportLb, gridBagConstraints);

    outputFolderLb.setLabelFor(outputFolderText);
    outputFolderLb.setText(options.getMsg("export_project_output_folder"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    add(outputFolderLb, gridBagConstraints);

    outputFolderText.setToolTipText(options.getMsg("edit_new_project_folder_tooltip"));
    outputFolderText.setMinimumSize(new java.awt.Dimension(280, 21));
    outputFolderText.setPreferredSize(new java.awt.Dimension(280, 21));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    add(outputFolderText, gridBagConstraints);

    outputFolderBtn.setText(options.getMsg("edit_new_project_folder_browse"));
    outputFolderBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        outputFolderBtnActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    add(outputFolderBtn, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
    add(spacer2, gridBagConstraints);

    allPrjChk.setText(options.getMsg("export_project_includeAll"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    add(allPrjChk, gridBagConstraints);

    exportScormChk.setText(options.getMsg("export_project_exportSCORM"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    add(exportScormChk, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents

  private JFileChooser chooser;

  private void outputFolderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputFolderBtnActionPerformed

    if (chooser == null) {
      chooser = new JFileChooser(outputFolder);
      chooser.setApproveButtonText(options.getMsg("export_project_selectFolder"));
      chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    }
    if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
      outputFolder = chooser.getSelectedFile().getAbsolutePath();
      outputFolderText.setText(outputFolder);
    }

  }//GEN-LAST:event_outputFolderBtnActionPerformed

  public void fillData() {
    outputFolderText.setText(outputFolder == null ? "" : outputFolder);
    allPrjChk.setSelected(exportAll);
    exportScormChk.setSelected(exportScorm);
  }

  public void getData() {
    outputFolder = StrUtils.nullableString(outputFolderText.getText());
    exportAll = allPrjChk.isSelected();
    exportScorm = exportScormChk.isSelected();
  }

  public static String[] prompt(ResourceBridge rb, Component parent, String inputPath, String exportBasePath) {
    String[] result = null;    
    ExportToJSDlg exportDlg = new ExportToJSDlg(rb);
    Messages msg = rb.getOptions().getMessages();
    String inputBase = (new File(inputPath)).getName();
    exportDlg.outputFolder = (new File(new File(exportBasePath), inputBase)).getPath();
    exportDlg.fillData();
    while (result == null) {
      if (!msg.showInputDlg(parent, exportDlg, "export_project_title")) {
        break;
      }
      exportDlg.getData();
      if (exportDlg.outputFolder == null) {
        msg.showErrorWarning(parent, "export_project_err_empty", null);
      } else {
        try {
          boolean folderOk = true;
          File outputFolderFile = new File(exportDlg.outputFolder);

          if (exportDlg.outputFolder.equals(inputPath)) {
            msg.showErrorWarning(parent, "export_project_err_sameFolder", null);
            folderOk = false;
          } else if (exportDlg.outputFolder.startsWith(inputPath)) {
            msg.showErrorWarning(parent, "export_project_err_nestedFolders", null);
            folderOk = false;
          } else if (outputFolderFile.exists() && outputFolderFile.isDirectory()) {
            if (outputFolderFile.list().length > 0) {
              folderOk = msg.showQuestionDlg(parent, "export_project_warning_noEmptyFolder", null, "yn") == Messages.YES;
            }
          } else if (!outputFolderFile.mkdirs()) {
            msg.showErrorWarning(parent, "edit_new_project_err_folderCreation", null);
            folderOk = false;
          }

          if (folderOk) {
            result = new String[]{exportDlg.outputFolder, inputPath,
              exportDlg.exportAll ? "true" : "false",
              exportDlg.exportScorm ? "true" : "false"};
          }
        } catch (Exception ex) {
          msg.showErrorWarning(parent, "ERROR", ex);
        }
      }
    }
    return result;
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JCheckBox allPrjChk;
  private javax.swing.JLabel exportLb;
  private javax.swing.JCheckBox exportScormChk;
  private javax.swing.JButton outputFolderBtn;
  private javax.swing.JLabel outputFolderLb;
  private javax.swing.JTextField outputFolderText;
  // End of variables declaration//GEN-END:variables

}
